import React from "react";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@styles/globals.css";
import "@styles/scss/main.scss";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "../context/AuthContext";
import EduBot from "@components/EduBot";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Edumate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body style={{ fontFamily: "var(--font-poppins), sans-serif" }}>
        {/* Auth Provider wrapping the app */}
        <AuthProvider>
          {children}
          <Toaster position="bottom-center" reverseOrder={false} />
          {/* AI Chatbot - Available on all pages */}
          <EduBot />
        </AuthProvider>
      </body>
    </html>
  );
}
