import React from "react";
import type { Metadata } from "next";
import "@styles/scss/main.scss";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Edumate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster position="bottom-center" reverseOrder={false} />
      </body>
    </html>
  );
}
