"use client";

import React, { useEffect, useState } from "react";
import { useAuth } from "../../../context/AuthContext";
import {
  collection,
  getDocs,
  query,
  where,
} from "firebase/firestore";
import { db } from "../../../config/firebaseConfig";
import toast from "react-hot-toast";
import {
  MdAssessment,
  MdDownload,
  MdPeople,
  MdBarChart,
  MdSchool,
  MdTrendingUp,
  MdPrint,
} from "react-icons/md";

interface StudentReport {
  id: string;
  name: string;
  regNumber: string;
  attendance: string;
  department: string;
  batch: string;
  email: string;
  grade?: string;
  cgpa?: number;
}

interface AnalyticsData {
  totalStudents: number;
  totalFaculty: number;
  totalDepartments: number;
  avgAttendance: number;
  departmentBreakdown: { name: string; count: number }[];
  attendanceDistribution: { range: string; count: number; color: string }[];
}

function generateSimpleReport(data: StudentReport[], title: string) {
  const rows = data
    .map(
      (s, i) =>
        `<tr>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;">${i + 1}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;">${s.name}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;">${s.regNumber || "—"}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;">${s.department}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;">${s.batch || "—"}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:center;">${s.attendance || "—"}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:center;">${s.cgpa ?? "—"}</td>
    </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>${title}</title>
  <style>
    body { font-family: Arial, sans-serif; color: #111; margin: 40px; }
    h1 { color: #1d4ed8; margin-bottom: 4px; }
    h3 { color: #6b7280; font-weight: normal; margin-top: 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    thead { background: #1d4ed8; color: white; }
    th { padding: 10px 12px; text-align: left; font-size: 13px; }
    td { font-size: 13px; color: #374151; }
    tr:hover td { background: #f9fafb; }
    .footer { margin-top: 30px; font-size: 12px; color: #9ca3af; text-align: center; }
    .meta { margin-top: 20px; display: flex; gap: 24px; font-size: 13px; color: #6b7280; }
    .meta span { background: #f3f4f6; padding: 4px 12px; border-radius: 20px; }
  </style>
</head>
<body>
  <h1>Edumate - ${title}</h1>
  <h3>Academic Report</h3>
  <div class="meta">
    <span>📅 Generated: ${new Date().toLocaleDateString()}</span>
    <span>👥 Total Students: ${data.length}</span>
  </div>
  <table>
    <thead>
      <tr>
        <th>#</th><th>Student Name</th><th>Reg. Number</th><th>Department</th><th>Batch</th><th>Attendance</th><th>CGPA</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="footer">Generated by Edumate Academic Management System • ${new Date().toISOString()}</div>
</body>
</html>`;
  return html;
}

function printReport(html: string) {
  const win = window.open("", "_blank");
  if (!win) {
    toast.error("Popup blocked. Please allow popups for this site.");
    return;
  }
  win.document.write(html);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 500);
}

export default function AdminReportPage() {
  useAuth(); // ensure auth context is available
  const [students, setStudents] = useState<StudentReport[]>([]);
  const [analytics, setAnalytics] = useState<AnalyticsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [filterDept, setFilterDept] = useState("All");
  const [filterBatch, setFilterBatch] = useState("All");
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      const [studentSnap, facultySnap, deptSnap] = await Promise.all([
        getDocs(collection(db, "students")),
        getDocs(collection(db, "faculty")),
        getDocs(collection(db, "departments")),
      ]);

      const studentData: StudentReport[] = studentSnap.docs.map((d) => {
        const data = d.data();
        return {
          id: d.id,
          name: data.info?.name || data.name || "Unknown",
          regNumber: data.info?.regNumber || data.regNumber || "",
          attendance: data.attendance || "N/A",
          department: data.department || "",
          batch: data.batch || "",
          email: data.email || "",
          cgpa: data.cgpa,
        };
      });
      setStudents(studentData);

      // Analytics
      const depts = deptSnap.docs.map((d) => ({ name: d.data().name, ...d.data() }));
      const deptBreakdown = depts.map((dept) => ({
        name: dept.name,
        count: studentData.filter((s) => s.department === dept.name).length,
      }));

      const parseAttendance = (att: string) => {
        const n = parseFloat(att);
        return isNaN(n) ? 0 : n;
      };

      const validAtt = studentData
        .map((s) => parseAttendance(s.attendance))
        .filter((a) => a > 0);
      const avgAttendance =
        validAtt.length > 0
          ? Math.round(validAtt.reduce((s, a) => s + a, 0) / validAtt.length)
          : 0;

      const attDist = [
        { range: "90-100%", min: 90, max: 100, color: "bg-green-500" },
        { range: "75-89%", min: 75, max: 89, color: "bg-blue-500" },
        { range: "60-74%", min: 60, max: 74, color: "bg-yellow-500" },
        { range: "Below 60%", min: 0, max: 59, color: "bg-red-500" },
      ].map(({ range, min, max, color }) => ({
        range,
        count: validAtt.filter((a) => a >= min && a <= max).length,
        color,
      }));

      setAnalytics({
        totalStudents: studentData.length,
        totalFaculty: facultySnap.size,
        totalDepartments: depts.length,
        avgAttendance,
        departmentBreakdown: deptBreakdown,
        attendanceDistribution: attDist,
      });
    } catch (e) {
      console.error(e);
      toast.error("Failed to load report data");
    } finally {
      setLoading(false);
    }
  };

  const departments = ["All", ...Array.from(new Set(students.map((s) => s.department).filter(Boolean)))];
  const batches = ["All", ...Array.from(new Set(students.map((s) => s.batch).filter(Boolean)))];

  const filteredStudents = students.filter((s) => {
    const matchDept = filterDept === "All" || s.department === filterDept;
    const matchBatch = filterBatch === "All" || s.batch === filterBatch;
    return matchDept && matchBatch;
  });

  const handleGenerateReport = () => {
    if (filteredStudents.length === 0) {
      toast.error("No students match the filter");
      return;
    }
    setGenerating(true);
    const title = `Student Progress Report${filterDept !== "All" ? ` - ${filterDept}` : ""}${filterBatch !== "All" ? ` (${filterBatch})` : ""}`;
    const html = generateSimpleReport(filteredStudents, title);
    printReport(html);
    toast.success("Report opened in new window. Use Ctrl+P to print/save as PDF.");
    setGenerating(false);
  };

  const exportCSV = () => {
    if (filteredStudents.length === 0) {
      toast.error("No data to export");
      return;
    }
    const header = ["Name", "Reg Number", "Department", "Batch", "Email", "Attendance", "CGPA"].join(",");
    const rows = filteredStudents.map((s) =>
      [s.name, s.regNumber, s.department, s.batch, s.email, s.attendance, s.cgpa ?? ""].join(",")
    );
    const csv = [header, ...rows].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `edumate_report_${new Date().toISOString().slice(0, 10)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("CSV exported successfully!");
  };

  if (loading) {
    return (
      <div className="p-6 bg-gray-50 min-h-screen animate-pulse">
        <div className="h-8 bg-gray-200 rounded w-48 mb-6" />
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          {[...Array(4)].map((_, i) => (
            <div key={i} className="h-24 bg-white rounded-xl border border-gray-100" />
          ))}
        </div>
        <div className="h-64 bg-white rounded-xl border border-gray-100" />
      </div>
    );
  }

  return (
    <div className="p-4 md:p-6 bg-gray-50 min-h-screen">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-8 gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
            <MdAssessment className="text-blue-600 text-3xl" />
            Report Generation
          </h1>
          <p className="text-gray-500 text-sm mt-1">
            Generate academic progress reports and analytics
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={exportCSV}
            className="flex items-center gap-2 px-4 py-2.5 bg-white border border-gray-200 text-gray-700 rounded-xl text-sm font-medium hover:bg-gray-50 transition"
          >
            <MdDownload className="text-lg" /> Export CSV
          </button>
          <button
            onClick={handleGenerateReport}
            disabled={generating}
            className="flex items-center gap-2 px-4 py-2.5 bg-blue-600 text-white rounded-xl text-sm font-medium hover:bg-blue-700 transition shadow-lg shadow-blue-200 disabled:opacity-60"
          >
            <MdPrint className="text-lg" />
            {generating ? "Generating..." : "Generate PDF Report"}
          </button>
        </div>
      </div>

      {/* Analytics Cards */}
      {analytics && (
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          {[
            {
              label: "Total Students",
              value: analytics.totalStudents,
              icon: MdPeople,
              color: "blue",
            },
            {
              label: "Total Faculty",
              value: analytics.totalFaculty,
              icon: MdSchool,
              color: "green",
            },
            {
              label: "Departments",
              value: analytics.totalDepartments,
              icon: MdBarChart,
              color: "purple",
            },
            {
              label: "Avg Attendance",
              value: analytics.avgAttendance + "%",
              icon: MdTrendingUp,
              color: analytics.avgAttendance >= 75 ? "green" : "red",
            },
          ].map((stat) => (
            <div
              key={stat.label}
              className="bg-white rounded-xl p-5 border border-gray-100 shadow-sm flex items-center gap-4"
            >
              <div
                className={`w-12 h-12 rounded-xl flex items-center justify-center bg-${stat.color}-50`}
              >
                <stat.icon className={`text-2xl text-${stat.color}-600`} />
              </div>
              <div>
                <p className="text-xs text-gray-500 font-medium">{stat.label}</p>
                <p className="text-2xl font-bold text-gray-900">{stat.value}</p>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Charts Row */}
      {analytics && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
          {/* Attendance Distribution */}
          <div className="bg-white rounded-xl border border-gray-100 p-5 shadow-sm">
            <h3 className="font-bold text-gray-900 mb-4">Attendance Distribution</h3>
            <div className="space-y-3">
              {analytics.attendanceDistribution.map((dist) => (
                <div key={dist.range}>
                  <div className="flex justify-between text-xs text-gray-600 mb-1">
                    <span>{dist.range}</span>
                    <span className="font-semibold">
                      {dist.count} student{dist.count !== 1 ? "s" : ""}
                    </span>
                  </div>
                  <div className="w-full bg-gray-100 rounded-full h-2.5">
                    <div
                      className={`${dist.color} h-2.5 rounded-full transition-all duration-500`}
                      style={{
                        width:
                          analytics.totalStudents > 0
                            ? `${(dist.count / analytics.totalStudents) * 100}%`
                            : "0%",
                      }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Department Breakdown */}
          <div className="bg-white rounded-xl border border-gray-100 p-5 shadow-sm">
            <h3 className="font-bold text-gray-900 mb-4">Students by Department</h3>
            {analytics.departmentBreakdown.length > 0 ? (
              <div className="space-y-3">
                {analytics.departmentBreakdown
                  .filter((d) => d.count > 0)
                  .sort((a, b) => b.count - a.count)
                  .map((dept, i) => {
                    const colors = [
                      "bg-blue-500",
                      "bg-green-500",
                      "bg-purple-500",
                      "bg-orange-500",
                      "bg-red-500",
                      "bg-indigo-500",
                    ];
                    return (
                      <div key={dept.name}>
                        <div className="flex justify-between text-xs text-gray-600 mb-1">
                          <span className="truncate max-w-[180px]" title={dept.name}>
                            {dept.name}
                          </span>
                          <span className="font-semibold">
                            {dept.count} ({Math.round((dept.count / analytics.totalStudents) * 100)}%)
                          </span>
                        </div>
                        <div className="w-full bg-gray-100 rounded-full h-2.5">
                          <div
                            className={`${colors[i % colors.length]} h-2.5 rounded-full transition-all duration-500`}
                            style={{
                              width:
                                analytics.totalStudents > 0
                                  ? `${(dept.count / analytics.totalStudents) * 100}%`
                                  : "0%",
                            }}
                          />
                        </div>
                      </div>
                    );
                  })}
              </div>
            ) : (
              <p className="text-gray-400 text-sm text-center py-4">No department data available</p>
            )}
          </div>
        </div>
      )}

      {/* Filters + Table */}
      <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="p-5 border-b border-gray-100 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h3 className="font-bold text-gray-900">Student Records</h3>
            <p className="text-xs text-gray-500 mt-0.5">
              {filteredStudents.length} of {students.length} students
            </p>
          </div>
          <div className="flex gap-3">
            <select
              value={filterDept}
              onChange={(e) => setFilterDept(e.target.value)}
              className="px-4 py-2 border border-gray-200 rounded-xl text-sm outline-none focus:ring-2 focus:ring-blue-500 bg-white"
            >
              {departments.map((d) => (
                <option key={d} value={d}>
                  {d}
                </option>
              ))}
            </select>
            <select
              value={filterBatch}
              onChange={(e) => setFilterBatch(e.target.value)}
              className="px-4 py-2 border border-gray-200 rounded-xl text-sm outline-none focus:ring-2 focus:ring-blue-500 bg-white"
            >
              {batches.map((b) => (
                <option key={b} value={b}>
                  {b}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="overflow-x-auto">
          {filteredStudents.length > 0 ? (
            <table className="min-w-full">
              <thead className="bg-gray-50 border-b border-gray-100">
                <tr>
                  {["#", "Name", "Reg. Number", "Department", "Batch", "Attendance", "CGPA"].map((h) => (
                    <th
                      key={h}
                      className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide"
                    >
                      {h}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-50">
                {filteredStudents.map((s, i) => {
                  const att = parseFloat(s.attendance);
                  const attColor = isNaN(att)
                    ? "text-gray-500"
                    : att >= 75
                    ? "text-green-600"
                    : "text-red-600";
                  return (
                    <tr key={s.id} className="hover:bg-gray-50 transition">
                      <td className="px-4 py-3 text-xs text-gray-400">{i + 1}</td>
                      <td className="px-4 py-3 text-sm font-medium text-gray-900">
                        {s.name}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-500 font-mono">
                        {s.regNumber || "—"}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-600">{s.department || "—"}</td>
                      <td className="px-4 py-3 text-sm text-gray-600">{s.batch || "—"}</td>
                      <td className={`px-4 py-3 text-sm font-semibold ${attColor}`}>
                        {s.attendance || "—"}
                      </td>
                      <td className="px-4 py-3 text-sm text-gray-700">
                        {s.cgpa ?? "—"}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          ) : (
            <div className="text-center py-16">
              <MdAssessment className="text-4xl text-gray-300 mx-auto mb-2" />
              <p className="text-gray-500 text-sm">No student records found</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
